plugins:
  - 'prettier-plugin-tailwindcss'
printWidth: 120
useTabs: false
tabWidth: 2
trailingComma: 'es5'
singleQuote: true
arrowParens: always
jsxSingleQuote: false
bracketSpacing: false
endOfLine: lf
